-- Synthetic schema exercising every feature the model carries. Loaded into a
-- scratch database, introspected, and the JSON committed as showcase.json.
-- Regenerate with:  just fixture   (see justfile)

CREATE SCHEMA shop;
CREATE SCHEMA audit;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

COMMENT ON SCHEMA shop IS 'Storefront';

CREATE TYPE shop.order_status AS ENUM ('draft', 'placed', 'shipped', 'cancelled');
COMMENT ON TYPE shop.order_status IS 'Lifecycle of an order';

CREATE DOMAIN shop.money_cents AS bigint NOT NULL DEFAULT 0 CHECK (VALUE >= 0);
COMMENT ON DOMAIN shop.money_cents IS 'Amounts are integers of cents';

CREATE DOMAIN shop.email AS text CHECK (VALUE ~ '@');

CREATE TYPE shop.address AS (street text, city text, "zip code" text);

CREATE TABLE shop.customers (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email       shop.email NOT NULL UNIQUE,
    full_name   text NOT NULL,
    "select"    text,                                   -- reserved word as identifier
    address     shop.address,
    tags        text[] NOT NULL DEFAULT '{}',
    referrer_id bigint REFERENCES shop.customers (id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.customers IS 'People who buy things';
COMMENT ON COLUMN shop.customers.email IS 'Login identifier; unique per customer';

CREATE TABLE shop.products (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sku         text NOT NULL,
    price       shop.money_cents,
    weight_g    integer CHECK (weight_g > 0),
    statuses    shop.order_status[] NOT NULL DEFAULT '{}',
    CONSTRAINT products_sku_key UNIQUE (sku)
);

CREATE TABLE shop.orders (
    id           bigserial PRIMARY KEY,
    customer_id  bigint NOT NULL REFERENCES shop.customers (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    status       shop.order_status NOT NULL DEFAULT 'draft',
    subtotal     shop.money_cents,
    tax          shop.money_cents,
    total        bigint GENERATED ALWAYS AS (subtotal + tax) STORED,
    placed_at    timestamptz,
    note         text,
    CONSTRAINT orders_placed_when_not_draft CHECK (status = 'draft' OR placed_at IS NOT NULL)
);
CREATE INDEX orders_customer_idx ON shop.orders (customer_id);
CREATE INDEX orders_open_idx ON shop.orders (placed_at DESC) WHERE status IN ('placed', 'shipped');
CREATE UNIQUE INDEX orders_note_lower_idx ON shop.orders (lower(note)) WHERE note IS NOT NULL;

-- Pure junction table: collapses to N:N in conceptual mode.
CREATE TABLE shop.order_products (
    order_id   bigint NOT NULL REFERENCES shop.orders (id) ON DELETE CASCADE,
    product_id uuid   NOT NULL REFERENCES shop.products (id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (order_id, product_id)
);

-- Composite primary key, referenced by a composite foreign key whose column
-- order differs from the referenced key's declaration order.
CREATE TABLE shop.warehouses (
    region  text NOT NULL,
    code    text NOT NULL,
    PRIMARY KEY (region, code)
);

CREATE TABLE shop.stock (
    product_id     uuid NOT NULL REFERENCES shop.products (id),
    warehouse_code text NOT NULL,
    region         text NOT NULL,
    quantity       integer NOT NULL DEFAULT 0,
    PRIMARY KEY (product_id, region, warehouse_code),
    CONSTRAINT stock_warehouse_fkey FOREIGN KEY (warehouse_code, region)
        REFERENCES shop.warehouses (code, region) DEFERRABLE INITIALLY DEFERRED
);

-- One-to-one: the FK columns are themselves the primary key.
CREATE TABLE shop.customer_profiles (
    customer_id bigint PRIMARY KEY REFERENCES shop.customers (id) ON DELETE CASCADE,
    bio         text
);

-- Exclusion constraint.
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE shop.promotions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id uuid NOT NULL REFERENCES shop.products (id),
    during     tstzrange NOT NULL,
    EXCLUDE USING gist (product_id WITH =, during WITH &&)
);

-- Partitioned table with a default partition and an unlogged child.
CREATE TABLE audit.events (
    id          bigint GENERATED ALWAYS AS IDENTITY,
    occurred_at timestamptz NOT NULL,
    customer_id bigint REFERENCES shop.customers (id),
    payload     jsonb NOT NULL,
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE TABLE audit.events_2026 PARTITION OF audit.events
    FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
CREATE TABLE audit.events_default PARTITION OF audit.events DEFAULT;

CREATE UNLOGGED TABLE audit.scratch (id int PRIMARY KEY);

-- Row level security with a restrictive policy and a role-scoped one.
CREATE ROLE showcase_reader NOLOGIN;
ALTER TABLE shop.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE shop.orders FORCE ROW LEVEL SECURITY;
CREATE POLICY orders_owner ON shop.orders
    FOR ALL USING (customer_id = current_setting('app.customer_id')::bigint)
    WITH CHECK (customer_id = current_setting('app.customer_id')::bigint);
CREATE POLICY orders_no_cancelled ON shop.orders AS RESTRICTIVE
    FOR SELECT TO showcase_reader USING (status <> 'cancelled');

-- A view over a view, and a materialized view.
CREATE VIEW shop.open_orders AS
    SELECT o.id, o.customer_id, o.total
    FROM shop.orders o
    WHERE o.status IN ('placed', 'shipped');
CREATE VIEW shop.open_orders_by_customer AS
    SELECT c.email, count(*) AS open_orders
    FROM shop.open_orders oo
    JOIN shop.customers c ON c.id = oo.customer_id
    GROUP BY c.email;
CREATE MATERIALIZED VIEW shop.daily_totals AS
    SELECT date_trunc('day', placed_at) AS day, sum(total) AS total
    FROM shop.orders
    GROUP BY 1
    WITH NO DATA;
COMMENT ON VIEW shop.open_orders IS 'Orders still in flight';
