//! PostgreSQL DDL for the objects the model carries.
//!
//! This is not `pg_dump` and must never be mistaken for it: functions, triggers,
//! grants, ownership, sequence state and foreign servers are not modelled, and
//! the header of every file says so. What it is good for is spinning up a
//! scratch copy of a schema, and reading a schema diff as SQL in a pull request.
//!
//! Statement order is dependency-correct: schemas, extensions, types, sequences,
//! tables, partitions, foreign keys (as `ALTER TABLE`, after every table exists,
//! because circular references are legal), indexes, views in dependency order,
//! row level security, comments.

use std::{
    collections::{BTreeSet, HashSet},
    fmt::Write,
};

use remus_core::{
    Error, Schema,
    emit::{
        DiagramOptions, Emitter,
        ident::{qualified, quote_ident, quote_literal},
    },
    model::{
        Column, ConstraintKind, Entity, EntityKind, Generated, Identity, PolicyCommand, RelationRef,
    },
};

/// Dispatch handle for this format. Rendering itself is the free function
/// below; the unit type exists so the CLI can hold every format as one
/// `dyn Emitter` without knowing which crates are linked in.
pub struct Sql;

impl Emitter for Sql {
    fn name(&self) -> &'static str {
        "sql"
    }

    fn extension(&self) -> &'static str {
        "sql"
    }

    fn render(&self, schema: &Schema, _options: &DiagramOptions) -> Result<String, Error> {
        Ok(self::render(schema))
    }
}

pub fn render(schema: &Schema) -> String {
    let mut out = String::new();
    write_header(&mut out, schema);
    write_schemas(&mut out, schema);
    write_extensions(&mut out, schema);
    write_types(&mut out, schema);
    write_sequences(&mut out, schema);
    write_tables(&mut out, schema);
    write_partitions(&mut out, schema);
    write_foreign_keys(&mut out, schema);
    write_indexes(&mut out, schema);
    write_views(&mut out, schema);
    write_row_level_security(&mut out, schema);
    write_comments(&mut out, schema);
    out
}

fn write_header(out: &mut String, schema: &Schema) {
    let _ = writeln!(
        out,
        "-- Schema DDL generated by remus from {} (PostgreSQL {}).\n\
         --\n\
         -- Covers only what remus models: schemas, extensions, enums, domains,\n\
         -- composite types, tables, constraints, indexes, partitions, views,\n\
         -- materialized views, row level security and comments.\n\
         -- NOT included: functions, triggers, grants, ownership, sequence state\n\
         -- (serial sequences are created bare), foreign tables and roles. Defaults\n\
         -- or policies that name those assume they already exist.\n\
         -- This is not a migration or a backup. Use pg_dump for that.\n",
        schema.database, schema.server_version
    );
}

fn write_schemas(out: &mut String, schema: &Schema) {
    let names: BTreeSet<&str> = schema
        .entities
        .iter()
        .map(|e| e.schema.as_str())
        .chain(schema.enums.iter().map(|e| e.schema.as_str()))
        .chain(schema.domains.iter().map(|d| d.schema.as_str()))
        .chain(schema.composites.iter().map(|c| c.schema.as_str()))
        .chain(schema.partitions.iter().map(|p| p.child_schema.as_str()))
        .chain(schema.extensions.iter().map(|x| x.schema.as_str()))
        .filter(|name| *name != "public")
        .collect();
    let any = !names.is_empty();
    for name in names {
        let _ = writeln!(out, "CREATE SCHEMA IF NOT EXISTS {};", quote_ident(name));
    }
    if any {
        out.push('\n');
    }
}

fn write_extensions(out: &mut String, schema: &Schema) {
    for extension in &schema.extensions {
        let _ = writeln!(
            out,
            "CREATE EXTENSION IF NOT EXISTS {} WITH SCHEMA {};",
            quote_ident(&extension.name),
            quote_ident(&extension.schema)
        );
    }
    if !schema.extensions.is_empty() {
        out.push('\n');
    }
}

/// Enums first, then domains, then composites: a domain over an enum and a
/// composite holding a domain are both common, the reverse orders are not.
fn write_types(out: &mut String, schema: &Schema) {
    for e in &schema.enums {
        let labels = e
            .labels
            .iter()
            .map(|l| quote_literal(l))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "CREATE TYPE {} AS ENUM ({labels});",
            qualified(&e.schema, &e.name)
        );
    }
    for d in &schema.domains {
        let _ = write!(
            out,
            "CREATE DOMAIN {} AS {}",
            qualified(&d.schema, &d.name),
            d.base_type
        );
        if let Some(default) = &d.default {
            let _ = write!(out, " DEFAULT {default}");
        }
        if d.not_null {
            out.push_str(" NOT NULL");
        }
        for constraint in &d.constraints {
            let _ = write!(out, " {constraint}");
        }
        out.push_str(";\n");
    }
    for c in &schema.composites {
        let attributes = c
            .attributes
            .iter()
            .map(|a| format!("{} {}", quote_ident(&a.name), a.r#type))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "CREATE TYPE {} AS ({attributes});",
            qualified(&c.schema, &c.name)
        );
    }
    if !schema.enums.is_empty() || !schema.domains.is_empty() || !schema.composites.is_empty() {
        out.push('\n');
    }
}

/// `serial` columns are plain columns whose default is `nextval(...)` on a
/// sequence pg_catalog owns on their behalf. The sequence has to exist before
/// the table; its current value and options are deliberately not reproduced.
fn write_sequences(out: &mut String, schema: &Schema) {
    let sequences: BTreeSet<&str> = schema
        .entities
        .iter()
        .flat_map(|e| e.columns.iter())
        .filter_map(|c| c.default.as_deref().and_then(owned_sequence))
        .collect();
    for sequence in &sequences {
        let _ = writeln!(out, "CREATE SEQUENCE IF NOT EXISTS {sequence};");
    }
    if !sequences.is_empty() {
        out.push('\n');
    }
}

/// The sequence name inside a `nextval('shop.orders_id_seq'::regclass)` default.
/// The literal is already quoted as needed because the catalog produced it.
fn owned_sequence(default: &str) -> Option<&str> {
    let inner = default.strip_prefix("nextval('")?;
    let (name, rest) = inner.split_once('\'')?;
    (rest == "::regclass)").then_some(name)
}

fn write_tables(out: &mut String, schema: &Schema) {
    for entity in &schema.entities {
        match entity.kind {
            EntityKind::Table | EntityKind::PartitionedTable => write_table(out, entity),
            EntityKind::ForeignTable => {
                let _ = writeln!(
                    out,
                    "-- Skipped foreign table {}: foreign servers are not modelled.\n",
                    qualified(&entity.schema, &entity.name)
                );
            }
            EntityKind::View | EntityKind::MaterializedView => {}
        }
    }
}

fn write_table(out: &mut String, entity: &Entity) {
    let persistence = if entity.unlogged { "UNLOGGED " } else { "" };
    let _ = writeln!(
        out,
        "CREATE {persistence}TABLE {} (",
        qualified(&entity.schema, &entity.name)
    );
    let mut lines: Vec<String> = entity.columns.iter().map(column_definition).collect();
    // Foreign keys are added after every table exists; everything else is
    // self-contained and reads best inline.
    lines.extend(
        entity
            .constraints
            .iter()
            .filter(|c| c.kind != ConstraintKind::ForeignKey)
            .map(|c| format!("CONSTRAINT {} {}", quote_ident(&c.name), c.definition)),
    );
    for (i, line) in lines.iter().enumerate() {
        let separator = if i + 1 < lines.len() { "," } else { "" };
        let _ = writeln!(out, "    {line}{separator}");
    }
    out.push(')');
    if let Some(key) = &entity.partition_key {
        let _ = write!(out, " PARTITION BY {key}");
    }
    out.push_str(";\n");

    for column in &entity.columns {
        if let Some(sequence) = column.default.as_deref().and_then(owned_sequence) {
            let _ = writeln!(
                out,
                "ALTER SEQUENCE {sequence} OWNED BY {}.{};",
                qualified(&entity.schema, &entity.name),
                quote_ident(&column.name)
            );
        }
    }
    out.push('\n');
}

fn column_definition(column: &Column) -> String {
    let mut line = format!("{} {}", quote_ident(&column.name), column.r#type);
    match (&column.generated, &column.identity, &column.default) {
        (Some(kind), _, Some(expression)) => {
            let storage = match kind {
                Generated::Stored => "STORED",
                Generated::Virtual => "VIRTUAL",
            };
            let _ = write!(line, " GENERATED ALWAYS AS ({expression}) {storage}");
        }
        (Some(_), _, None) => {}
        (None, Some(identity), _) => {
            let when = match identity {
                Identity::Always => "ALWAYS",
                Identity::ByDefault => "BY DEFAULT",
            };
            let _ = write!(line, " GENERATED {when} AS IDENTITY");
        }
        (None, None, Some(default)) => {
            let _ = write!(line, " DEFAULT {default}");
        }
        (None, None, None) => {}
    }
    if column.not_null {
        line.push_str(" NOT NULL");
    }
    line
}

fn write_partitions(out: &mut String, schema: &Schema) {
    for p in &schema.partitions {
        let bound = p.bound.as_deref().unwrap_or("DEFAULT");
        let _ = writeln!(
            out,
            "CREATE TABLE {} PARTITION OF {} {bound};",
            qualified(&p.child_schema, &p.child),
            qualified(&p.parent_schema, &p.parent)
        );
    }
    if !schema.partitions.is_empty() {
        out.push('\n');
    }
}

fn write_foreign_keys(out: &mut String, schema: &Schema) {
    let mut any = false;
    for entity in schema.entities.iter().filter(|e| e.kind.is_table()) {
        for fk in entity.foreign_keys() {
            any = true;
            let _ = writeln!(
                out,
                "ALTER TABLE {} ADD CONSTRAINT {} {};",
                qualified(&entity.schema, &entity.name),
                quote_ident(&fk.name),
                fk.definition
            );
        }
    }
    if any {
        out.push('\n');
    }
}

fn write_indexes(out: &mut String, schema: &Schema) {
    let mut any = false;
    for entity in &schema.entities {
        for index in &entity.indexes {
            any = true;
            let _ = writeln!(out, "{};", index.definition);
        }
    }
    if any {
        out.push('\n');
    }
}

/// Views in dependency order: a view over a view must come second. The
/// catalog guarantees the graph is acyclic, so the loop always terminates.
fn write_views(out: &mut String, schema: &Schema) {
    let mut pending: Vec<&Entity> = schema
        .entities
        .iter()
        .filter(|e| e.kind.is_view())
        .collect();
    let mut created: HashSet<RelationRef> = HashSet::new();
    while !pending.is_empty() {
        let (ready, blocked): (Vec<&Entity>, Vec<&Entity>) =
            pending.into_iter().partition(|view| {
                view.depends_on.iter().all(|dep| {
                    created.contains(dep) || schema.entity(dep).is_none_or(|e| !e.kind.is_view())
                })
            });
        // Nothing ready only happens when a dependency lies outside the selected
        // schemas; emit what is left rather than loop forever.
        let (batch, rest) = if ready.is_empty() {
            (blocked, Vec::new())
        } else {
            (ready, blocked)
        };
        for view in batch {
            write_view(out, view);
            created.insert(view.reference());
        }
        pending = rest;
    }
}

fn write_view(out: &mut String, view: &Entity) {
    let Some(definition) = &view.view_definition else {
        return;
    };
    let body = definition.trim().trim_end_matches(';').trim_end();
    let (keyword, suffix) = match view.kind {
        EntityKind::MaterializedView => ("MATERIALIZED VIEW", "\nWITH NO DATA"),
        EntityKind::View
        | EntityKind::Table
        | EntityKind::PartitionedTable
        | EntityKind::ForeignTable => ("VIEW", ""),
    };
    let _ = writeln!(
        out,
        "CREATE {keyword} {} AS\n{body}{suffix};\n",
        qualified(&view.schema, &view.name)
    );
}

fn write_row_level_security(out: &mut String, schema: &Schema) {
    let mut any = false;
    for entity in schema
        .entities
        .iter()
        .filter(|e| e.rls || !e.policies.is_empty())
    {
        any = true;
        let table = qualified(&entity.schema, &entity.name);
        if entity.rls {
            let _ = writeln!(out, "ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;");
        }
        if entity.rls_forced {
            let _ = writeln!(out, "ALTER TABLE {table} FORCE ROW LEVEL SECURITY;");
        }
        for policy in &entity.policies {
            let _ = write!(
                out,
                "CREATE POLICY {} ON {table}",
                quote_ident(&policy.name)
            );
            if !policy.permissive {
                out.push_str(" AS RESTRICTIVE");
            }
            let command = match policy.command {
                PolicyCommand::All => "ALL",
                PolicyCommand::Select => "SELECT",
                PolicyCommand::Insert => "INSERT",
                PolicyCommand::Update => "UPDATE",
                PolicyCommand::Delete => "DELETE",
            };
            let _ = write!(out, " FOR {command}");
            if !policy.roles.is_empty() {
                let roles = policy
                    .roles
                    .iter()
                    .map(|r| quote_ident(r))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = write!(out, " TO {roles}");
            }
            if let Some(using) = &policy.using {
                let _ = write!(out, " USING {using}");
            }
            if let Some(check) = &policy.check {
                let _ = write!(out, " WITH CHECK {check}");
            }
            out.push_str(";\n");
        }
    }
    if any {
        out.push('\n');
    }
}

fn write_comments(out: &mut String, schema: &Schema) {
    for e in &schema.enums {
        if let Some(comment) = &e.comment {
            let _ = writeln!(
                out,
                "COMMENT ON TYPE {} IS {};",
                qualified(&e.schema, &e.name),
                quote_literal(comment)
            );
        }
    }
    for d in &schema.domains {
        if let Some(comment) = &d.comment {
            let _ = writeln!(
                out,
                "COMMENT ON DOMAIN {} IS {};",
                qualified(&d.schema, &d.name),
                quote_literal(comment)
            );
        }
    }
    for c in &schema.composites {
        if let Some(comment) = &c.comment {
            let _ = writeln!(
                out,
                "COMMENT ON TYPE {} IS {};",
                qualified(&c.schema, &c.name),
                quote_literal(comment)
            );
        }
    }
    for entity in &schema.entities {
        let keyword = match entity.kind {
            EntityKind::Table | EntityKind::PartitionedTable => "TABLE",
            EntityKind::View => "VIEW",
            EntityKind::MaterializedView => "MATERIALIZED VIEW",
            EntityKind::ForeignTable => continue,
        };
        let table = qualified(&entity.schema, &entity.name);
        if let Some(comment) = &entity.comment {
            let _ = writeln!(
                out,
                "COMMENT ON {keyword} {table} IS {};",
                quote_literal(comment)
            );
        }
        for column in &entity.columns {
            if let Some(comment) = &column.comment {
                let _ = writeln!(
                    out,
                    "COMMENT ON COLUMN {table}.{} IS {};",
                    quote_ident(&column.name),
                    quote_literal(comment)
                );
            }
        }
        for constraint in &entity.constraints {
            if let Some(comment) = &constraint.comment {
                let _ = writeln!(
                    out,
                    "COMMENT ON CONSTRAINT {} ON {table} IS {};",
                    quote_ident(&constraint.name),
                    quote_literal(comment)
                );
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use remus_core::{Schema, fixtures::SHOWCASE};

    use super::{owned_sequence, render};

    fn showcase() -> Schema {
        Schema::from_json(SHOWCASE).unwrap()
    }

    #[test]
    fn serial_sequences_are_recognised() {
        assert_eq!(
            owned_sequence("nextval('shop.orders_id_seq'::regclass)"),
            Some("shop.orders_id_seq")
        );
        assert_eq!(owned_sequence("nextval('seq'::regclass) + 1"), None);
        assert_eq!(owned_sequence("now()"), None);
    }

    #[test]
    fn every_table_exists_before_any_foreign_key() {
        let sql = render(&showcase());
        let last_create = sql.rfind("CREATE TABLE").unwrap();
        let first_fk = sql.find("FOREIGN KEY").unwrap();
        assert!(
            last_create < first_fk,
            "a FOREIGN KEY appears before the last CREATE TABLE"
        );
        assert!(
            !sql[..first_fk].contains("REFERENCES"),
            "an inline REFERENCES slipped in"
        );
    }

    #[test]
    fn views_come_after_what_they_read() {
        let sql = render(&showcase());
        let base = sql.find("CREATE VIEW shop.open_orders AS").unwrap();
        let derived = sql
            .find("CREATE VIEW shop.open_orders_by_customer AS")
            .unwrap();
        assert!(base < derived);
        assert!(sql.contains("CREATE MATERIALIZED VIEW shop.daily_totals AS"));
        assert!(sql.contains("\nWITH NO DATA;"));
    }

    #[test]
    fn column_clauses_cover_identity_generated_and_serial() {
        let sql = render(&showcase());
        assert!(sql.contains("id bigint GENERATED ALWAYS AS IDENTITY NOT NULL"));
        assert!(sql.contains("id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assert!(sql.contains(
            "total bigint GENERATED ALWAYS AS (((subtotal)::bigint + (tax)::bigint)) STORED"
        ));
        assert!(sql.contains("CREATE SEQUENCE IF NOT EXISTS shop.orders_id_seq;"));
        assert!(sql.contains("ALTER SEQUENCE shop.orders_id_seq OWNED BY shop.orders.id;"));
        assert!(sql.contains("\"select\" text"));
    }

    #[test]
    fn partitions_and_policies_are_emitted() {
        let sql = render(&showcase());
        assert!(sql.contains(") PARTITION BY RANGE (occurred_at);"));
        assert!(
            sql.contains("CREATE TABLE audit.events_default PARTITION OF audit.events DEFAULT;")
        );
        assert!(sql.contains("ALTER TABLE shop.orders FORCE ROW LEVEL SECURITY;"));
        assert!(sql.contains(
            "CREATE POLICY orders_no_cancelled ON shop.orders AS RESTRICTIVE FOR SELECT TO showcase_reader USING"
        ));
    }
}
