//! DBML output, for dbdiagram.io, DrawSQL and ChartDB.
//!
//! A distribution channel, not a representation: DBML has no views, policies,
//! partitions, generated columns or check constraints. What cannot be expressed
//! is carried in notes so it is at least visible in the editor; the JSON export
//! remains the authoritative model. The emitter is one-directional by design:
//! reading DBML back would produce a poorer model than the catalog gives.

use std::{collections::HashSet, fmt::Write};

use super::DiagramOptions;
use crate::{
    Schema,
    model::{
        Column, Constraint, ConstraintKind, Entity, Index, ReferentialAction, RelationRef, TypeKind,
    },
};

pub fn render(schema: &Schema, options: &DiagramOptions) -> String {
    let collapsed: HashSet<RelationRef> = if options.conceptual {
        schema
            .entities
            .iter()
            .filter(|e| e.is_junction())
            .map(Entity::reference)
            .collect()
    } else {
        HashSet::new()
    };
    let is_table = |e: &Entity| !e.kind.is_view() && !collapsed.contains(&e.reference());

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by remus from {} (PostgreSQL {}).",
        schema.database, schema.server_version
    );
    let _ = writeln!(
        out,
        "// DBML is lossy: views, policies, partitions, generated columns and check\n\
         // constraints survive only as notes. The JSON export is authoritative.\n"
    );

    for e in &schema.enums {
        let _ = writeln!(out, "Enum {} {{", qualified(&e.schema, &e.name));
        for label in &e.labels {
            let _ = writeln!(out, "  \"{}\"", label.replace('"', "\\\""));
        }
        let _ = writeln!(out, "}}");
        if let Some(comment) = &e.comment {
            let _ = writeln!(out, "// {}", comment.replace(['\n', '\r'], " "));
        }
        out.push('\n');
    }

    for entity in schema.entities.iter().filter(|e| is_table(e)) {
        write_table(&mut out, schema, entity);
    }

    if schema.is_multi_schema() {
        let mut schemas: Vec<&str> = schema.entities.iter().map(|e| e.schema.as_str()).collect();
        schemas.sort_unstable();
        schemas.dedup();
        for name in schemas {
            let members: Vec<_> = schema
                .entities
                .iter()
                .filter(|e| e.schema == name && is_table(e))
                .collect();
            if members.is_empty() {
                continue;
            }
            let _ = writeln!(out, "TableGroup {} {{", ident(name));
            for member in members {
                let _ = writeln!(out, "  {}", qualified(&member.schema, &member.name));
            }
            let _ = writeln!(out, "}}\n");
        }
    }

    for entity in &schema.entities {
        if collapsed.contains(&entity.reference()) {
            write_many_to_many(&mut out, entity);
            continue;
        }
        if !is_table(entity) {
            continue;
        }
        for fk in entity.foreign_keys() {
            if fk.target().is_some_and(|t| collapsed.contains(&t)) {
                continue;
            }
            write_ref(&mut out, entity, fk);
        }
    }

    let views: Vec<_> = schema
        .entities
        .iter()
        .filter(|e| e.kind.is_view())
        .collect();
    if !views.is_empty() {
        let _ = writeln!(out, "\n// Views are not representable in DBML:");
        for view in views {
            let _ = writeln!(out, "//   {}", qualified(&view.schema, &view.name));
        }
    }

    out
}

fn write_table(out: &mut String, schema: &Schema, entity: &Entity) {
    let _ = writeln!(out, "Table {} {{", qualified(&entity.schema, &entity.name));
    for column in &entity.columns {
        let settings = column_settings(schema, entity, column);
        let _ = write!(out, "  {} {}", ident(&column.name), column_type(column));
        if settings.is_empty() {
            out.push('\n');
        } else {
            let _ = writeln!(out, " [{}]", settings.join(", "));
        }
    }

    let composite_keys: Vec<&Constraint> = entity
        .constraints
        .iter()
        .filter(|c| {
            matches!(c.kind, ConstraintKind::PrimaryKey | ConstraintKind::Unique)
                && c.columns.len() > 1
        })
        .collect();
    if !composite_keys.is_empty() || !entity.indexes.is_empty() {
        let _ = writeln!(out, "\n  indexes {{");
        for key in composite_keys {
            let columns = key
                .columns
                .iter()
                .map(|c| ident(c))
                .collect::<Vec<_>>()
                .join(", ");
            let kind = if key.kind == ConstraintKind::PrimaryKey {
                "pk".to_owned()
            } else {
                format!("unique, name: {}", note(&key.name))
            };
            let _ = writeln!(out, "    ({columns}) [{kind}]");
        }
        for index in &entity.indexes {
            write_index(out, index);
        }
        let _ = writeln!(out, "  }}");
    }

    let facts = table_facts(entity);
    if !facts.is_empty() {
        let _ = writeln!(out, "\n  Note: {}", note(&facts.join("; ")));
    }
    let _ = writeln!(out, "}}\n");
}

fn column_settings(schema: &Schema, entity: &Entity, column: &Column) -> Vec<String> {
    let mut settings = Vec::new();
    if entity
        .primary_key()
        .is_some_and(|pk| pk.columns == [column.name.as_str()])
    {
        settings.push("pk".to_owned());
    }
    if column.not_null {
        settings.push("not null".to_owned());
    }
    if entity.has_single_unique(&column.name) {
        settings.push("unique".to_owned());
    }
    let is_serial = column
        .default
        .as_deref()
        .is_some_and(|d| d.starts_with("nextval("));
    if column.identity.is_some() || is_serial {
        settings.push("increment".to_owned());
    } else if let (Some(default), None) = (&column.default, &column.generated) {
        settings.push(format!("default: {}", default_value(default)));
    }
    let mut remarks = Vec::new();
    if let Some(comment) = &column.comment {
        remarks.push(comment.clone());
    }
    match column.type_kind {
        TypeKind::Domain => remarks.push(match schema.domain_of(column) {
            Some(domain) => format!("domain over {}", domain.base_type),
            None => "domain".to_owned(),
        }),
        TypeKind::Composite => remarks.push("composite type".to_owned()),
        TypeKind::Base
        | TypeKind::Enum
        | TypeKind::Range
        | TypeKind::Multirange
        | TypeKind::Pseudo => {}
    }
    if let (Some(_), Some(expression)) = (&column.generated, &column.default) {
        remarks.push(format!("generated as {expression}"));
    }
    if !remarks.is_empty() {
        settings.push(format!("note: {}", note(&remarks.join("; "))));
    }
    settings
}

/// Enums are referenced by name so the editor links them; everything else is
/// the Postgres type text, quoted when it contains spaces.
fn column_type(column: &Column) -> String {
    if column.type_kind == TypeKind::Enum && !column.is_array {
        return qualified(&column.type_schema, &column.type_name);
    }
    let raw = &column.r#type;
    let plain = raw
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '(' | ')' | ',' | '[' | ']' | '.'));
    if plain {
        raw.clone()
    } else {
        format!("\"{raw}\"")
    }
}

/// DBML wants numbers and booleans bare, strings single-quoted and anything
/// else in backticks as an expression.
fn default_value(default: &str) -> String {
    let is_number = default.parse::<f64>().is_ok();
    if is_number || default == "true" || default == "false" {
        return default.to_owned();
    }
    if let Some(literal) = string_literal(default) {
        return format!("'{}'", literal.replace('\'', "\\'"));
    }
    format!("`{}`", default.replace('`', "'"))
}

/// `'draft'::shop.order_status` → `draft`. Only whole-literal defaults qualify;
/// anything with an operator stays an expression.
fn string_literal(default: &str) -> Option<String> {
    let body = default.strip_prefix('\'')?;
    let mut literal = String::new();
    let mut chars = body.chars().peekable();
    while let Some(c) = chars.next() {
        if c != '\'' {
            literal.push(c);
            continue;
        }
        if chars.peek() == Some(&'\'') {
            chars.next();
            literal.push('\'');
            continue;
        }
        let rest: String = chars.collect();
        return is_bare_cast(&rest).then_some(literal);
    }
    None
}

/// Nothing, or a single `::type` cast: `::text`, `::character varying(10)`,
/// `::shop.order_status[]`. An operator after the literal means it is an
/// expression, not a literal.
fn is_bare_cast(rest: &str) -> bool {
    match rest.strip_prefix("::") {
        None => rest.is_empty(),
        Some(type_name) => {
            !type_name.is_empty()
                && type_name.chars().all(|c| {
                    c.is_ascii_alphanumeric()
                        || matches!(c, '_' | '.' | '"' | '[' | ']' | '(' | ')' | ',' | ' ')
                })
        }
    }
}

fn write_index(out: &mut String, index: &Index) {
    let Some(parsed) = ParsedIndex::parse(&index.definition) else {
        let _ = writeln!(out, "    // {}", index.definition);
        return;
    };
    let items = parsed
        .items
        .iter()
        .map(|item| index_item(item))
        .collect::<Vec<_>>()
        .join(", ");
    let mut settings = vec![format!("name: {}", note(&index.name))];
    if index.unique {
        settings.insert(0, "unique".to_owned());
    }
    let mut remarks = Vec::new();
    if parsed.method != "btree" {
        remarks.push(format!("using {}", parsed.method));
    }
    if let Some(predicate) = &parsed.predicate {
        remarks.push(format!("where {predicate}"));
    }
    if !remarks.is_empty() {
        settings.push(format!("note: {}", note(&remarks.join("; "))));
    }
    let _ = writeln!(out, "    ({items}) [{}]", settings.join(", "));
}

/// A bare column name stays a name; anything else (`lower(note)`, `placed_at
/// DESC`) becomes a backtick expression, which DBML accepts.
fn index_item(item: &str) -> String {
    let bare = item.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && item.chars().next().is_some_and(|c| !c.is_ascii_digit());
    if bare {
        ident(item)
    } else if let Some(quoted) = item.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        ident(&quoted.replace("\"\"", "\""))
    } else {
        format!("`{}`", item.replace('`', "'"))
    }
}

/// The parts of a `pg_get_indexdef` string DBML can use.
struct ParsedIndex {
    method: String,
    items: Vec<String>,
    predicate: Option<String>,
}

impl ParsedIndex {
    fn parse(definition: &str) -> Option<Self> {
        let after_using = definition.split_once(" USING ")?.1;
        let (method, rest) = after_using.split_once(" (")?;
        let close = matching_paren(rest)?;
        let items = split_top_level(&rest[..close]);
        let tail = rest[close + 1..].trim();
        let predicate = tail.strip_prefix("WHERE ").map(|p| {
            p.strip_prefix('(')
                .and_then(|p| p.strip_suffix(')'))
                .unwrap_or(p)
                .to_owned()
        });
        Some(Self {
            method: method.to_owned(),
            items,
            predicate,
        })
    }
}

/// Index of the `)` closing the `(` that precedes `text`.
fn matching_paren(text: &str) -> Option<usize> {
    let mut depth = 1usize;
    let mut in_string = false;
    for (i, c) in text.char_indices() {
        match c {
            '\'' => in_string = !in_string,
            '(' if !in_string => depth += 1,
            ')' if !in_string => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

fn split_top_level(text: &str) -> Vec<String> {
    let mut items = Vec::new();
    let mut depth = 0usize;
    let mut in_string = false;
    let mut current = String::new();
    for c in text.chars() {
        match c {
            '\'' => in_string = !in_string,
            '(' if !in_string => depth += 1,
            ')' if !in_string => depth = depth.saturating_sub(1),
            ',' if !in_string && depth == 0 => {
                items.push(current.trim().to_owned());
                current.clear();
                continue;
            }
            _ => {}
        }
        current.push(c);
    }
    if !current.trim().is_empty() {
        items.push(current.trim().to_owned());
    }
    items
}

fn table_facts(entity: &Entity) -> Vec<String> {
    let mut facts = Vec::new();
    if let Some(comment) = &entity.comment {
        facts.push(comment.clone());
    }
    if entity.unlogged {
        facts.push("unlogged".to_owned());
    }
    if let Some(key) = &entity.partition_key {
        facts.push(format!("partitioned by {key}"));
    }
    if entity.rls {
        let mut rls = format!("row level security ({} policies)", entity.policies.len());
        if entity.rls_forced {
            rls.push_str(", forced");
        }
        facts.push(rls);
    }
    for constraint in &entity.constraints {
        match constraint.kind {
            ConstraintKind::Check | ConstraintKind::Exclusion => {
                facts.push(format!("{}: {}", constraint.name, constraint.definition));
            }
            ConstraintKind::PrimaryKey | ConstraintKind::Unique | ConstraintKind::ForeignKey => {}
        }
    }
    facts
}

fn write_ref(out: &mut String, entity: &Entity, fk: &Constraint) {
    let (Some(ref_schema), Some(ref_table)) = (&fk.ref_schema, &fk.ref_table) else {
        return;
    };
    let relation = if entity.is_unique_set(&fk.columns) {
        "-"
    } else {
        ">"
    };
    let mut settings = Vec::new();
    if let Some(action) = fk.on_delete.as_ref().and_then(action_keyword) {
        settings.push(format!("delete: {action}"));
    }
    if let Some(action) = fk.on_update.as_ref().and_then(action_keyword) {
        settings.push(format!("update: {action}"));
    }
    let suffix = if settings.is_empty() {
        String::new()
    } else {
        format!(" [{}]", settings.join(", "))
    };
    let _ = writeln!(
        out,
        "Ref {}: {}.{} {relation} {}.{}{suffix}",
        ident(&fk.name),
        qualified(&entity.schema, &entity.name),
        column_list(&fk.columns),
        qualified(ref_schema, ref_table),
        column_list(&fk.ref_columns),
    );
}

/// DBML has native many-to-many; a collapsed junction becomes one such ref
/// between the two keys it joined, named after the table it replaces.
fn write_many_to_many(out: &mut String, junction: &Entity) {
    let ends: Vec<_> = junction
        .foreign_keys()
        .filter_map(|fk| fk.target().map(|t| (t, &fk.ref_columns)))
        .collect();
    let [(left, left_columns), (right, right_columns)] = ends.as_slice() else {
        return;
    };
    let _ = writeln!(
        out,
        "Ref {}: {}.{} <> {}.{}",
        ident(&junction.name),
        qualified(&left.schema, &left.name),
        column_list(left_columns),
        qualified(&right.schema, &right.name),
        column_list(right_columns),
    );
}

fn column_list(columns: &[String]) -> String {
    match columns {
        [single] => ident(single),
        many => format!(
            "({})",
            many.iter().map(|c| ident(c)).collect::<Vec<_>>().join(", ")
        ),
    }
}

/// `NO ACTION` is the default and DBML has no keyword for it.
fn action_keyword(action: &ReferentialAction) -> Option<&'static str> {
    match action {
        ReferentialAction::Cascade => Some("cascade"),
        ReferentialAction::Restrict => Some("restrict"),
        ReferentialAction::SetNull => Some("set null"),
        ReferentialAction::SetDefault => Some("set default"),
        ReferentialAction::NoAction => None,
    }
}

/// DBML identifiers are always double-quoted here: the grammar is fussier than
/// SQL about bare words and the editors render quotes away.
fn ident(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\\\""))
}

fn qualified(schema: &str, name: &str) -> String {
    format!("{}.{}", ident(schema), ident(name))
}

fn note(text: &str) -> String {
    format!(
        "'{}'",
        text.replace('\\', "\\\\")
            .replace('\'', "\\'")
            .replace(['\n', '\r'], " ")
    )
}

#[cfg(test)]
mod tests {
    use super::{ParsedIndex, default_value, render};
    use crate::{Schema, emit::DiagramOptions};

    const SHOWCASE: &str = include_str!("../../tests/fixtures/showcase.json");

    #[test]
    fn defaults_take_dbml_shapes() {
        assert_eq!(default_value("0"), "0");
        assert_eq!(default_value("true"), "true");
        assert_eq!(default_value("'draft'::shop.order_status"), "'draft'");
        assert_eq!(default_value("'it''s'::text"), "'it\\'s'");
        assert_eq!(default_value("now()"), "`now()`");
        assert_eq!(
            default_value("'a'::text || 'b'::text"),
            "`'a'::text || 'b'::text`"
        );
    }

    #[test]
    fn index_definitions_split_into_items_and_predicate() {
        let parsed = ParsedIndex::parse(
            "CREATE UNIQUE INDEX i ON shop.orders USING btree (lower(note), placed_at DESC) WHERE (note IS NOT NULL)",
        )
        .unwrap();
        assert_eq!(parsed.method, "btree");
        assert_eq!(parsed.items, ["lower(note)", "placed_at DESC"]);
        assert_eq!(parsed.predicate.as_deref(), Some("note IS NOT NULL"));

        let plain = ParsedIndex::parse("CREATE INDEX i ON t USING gin (payload)").unwrap();
        assert_eq!(plain.items, ["payload"]);
        assert_eq!(plain.method, "gin");
        assert!(plain.predicate.is_none());
    }

    #[test]
    fn composite_keys_and_one_to_one_are_expressed() {
        let schema = Schema::from_json(SHOWCASE).unwrap();
        let out = render(&schema, &DiagramOptions::default());
        assert!(out.contains("(\"order_id\", \"product_id\") [pk]"));
        assert!(out.contains(
            "Ref \"stock_warehouse_fkey\": \"shop\".\"stock\".(\"warehouse_code\", \"region\") > \"shop\".\"warehouses\".(\"code\", \"region\")"
        ));
        assert!(out.contains(
            "Ref \"customer_profiles_customer_id_fkey\": \"shop\".\"customer_profiles\".\"customer_id\" - \"shop\".\"customers\".\"id\" [delete: cascade]"
        ));
    }

    #[test]
    fn conceptual_mode_emits_many_to_many() {
        let schema = Schema::from_json(SHOWCASE).unwrap();
        let out = render(
            &schema,
            &DiagramOptions {
                conceptual: true,
                ..DiagramOptions::default()
            },
        );
        assert!(!out.contains("Table \"shop\".\"order_products\""));
        assert!(out.contains(
            "Ref \"order_products\": \"shop\".\"orders\".\"id\" <> \"shop\".\"products\".\"id\""
        ));
    }
}
