-- Schema DDL generated by remus from remus_showcase (PostgreSQL 16.14 (Debian 16.14-1.pgdg13+1)).
--
-- Covers only what remus models: schemas, extensions, enums, domains,
-- composite types, tables, constraints, indexes, partitions, views,
-- materialized views, row level security and comments.
-- NOT included: functions, triggers, grants, ownership, sequence state
-- (serial sequences are created bare), foreign tables and roles. Defaults
-- or policies that name those assume they already exist.
-- This is not a migration or a backup. Use pg_dump for that.

CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS shop;

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TYPE shop.order_status AS ENUM ('draft', 'placed', 'shipped', 'cancelled');
CREATE DOMAIN shop.email AS text CHECK ((VALUE ~ '@'::text));
CREATE DOMAIN shop.money_cents AS bigint DEFAULT 0 NOT NULL CHECK ((VALUE >= 0));
CREATE TYPE shop.address AS (street text, city text, "zip code" text);

CREATE SEQUENCE IF NOT EXISTS shop.orders_id_seq;

CREATE TABLE audit.events (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    customer_id bigint,
    payload jsonb NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE UNLOGGED TABLE audit.scratch (
    id integer NOT NULL,
    CONSTRAINT scratch_pkey PRIMARY KEY (id)
);

CREATE TABLE shop.customer_profiles (
    customer_id bigint NOT NULL,
    bio text,
    CONSTRAINT customer_profiles_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE shop.customers (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    email shop.email NOT NULL,
    full_name text NOT NULL,
    "select" text,
    address shop.address,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    referrer_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE shop.order_products (
    order_id bigint NOT NULL,
    product_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT order_products_pkey PRIMARY KEY (order_id, product_id)
);

CREATE TABLE shop.orders (
    id bigint DEFAULT nextval('shop.orders_id_seq'::regclass) NOT NULL,
    customer_id bigint NOT NULL,
    status shop.order_status DEFAULT 'draft'::shop.order_status NOT NULL,
    subtotal shop.money_cents,
    tax shop.money_cents,
    total bigint GENERATED ALWAYS AS (((subtotal)::bigint + (tax)::bigint)) STORED,
    placed_at timestamp with time zone,
    note text,
    CONSTRAINT orders_placed_when_not_draft CHECK (((status = 'draft'::shop.order_status) OR (placed_at IS NOT NULL))),
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);
ALTER SEQUENCE shop.orders_id_seq OWNED BY shop.orders.id;

CREATE TABLE shop.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sku text NOT NULL,
    price shop.money_cents,
    weight_g integer,
    statuses shop.order_status[] DEFAULT '{}'::shop.order_status[] NOT NULL,
    CONSTRAINT products_weight_g_check CHECK ((weight_g > 0)),
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_sku_key UNIQUE (sku)
);

CREATE TABLE shop.promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id uuid NOT NULL,
    during tstzrange NOT NULL,
    CONSTRAINT promotions_pkey PRIMARY KEY (id),
    CONSTRAINT promotions_product_id_during_excl EXCLUDE USING gist (product_id WITH =, during WITH &&)
);

CREATE TABLE shop.stock (
    product_id uuid NOT NULL,
    warehouse_code text NOT NULL,
    region text NOT NULL,
    quantity integer DEFAULT 0 NOT NULL,
    CONSTRAINT stock_pkey PRIMARY KEY (product_id, region, warehouse_code)
);

CREATE TABLE shop.warehouses (
    region text NOT NULL,
    code text NOT NULL,
    CONSTRAINT warehouses_pkey PRIMARY KEY (region, code)
);

CREATE TABLE audit.events_2026 PARTITION OF audit.events FOR VALUES FROM ('2026-01-01 00:00:00+00') TO ('2027-01-01 00:00:00+00');
CREATE TABLE audit.events_default PARTITION OF audit.events DEFAULT;

ALTER TABLE audit.events ADD CONSTRAINT events_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES shop.customers(id);
ALTER TABLE shop.customer_profiles ADD CONSTRAINT customer_profiles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES shop.customers(id) ON DELETE CASCADE;
ALTER TABLE shop.customers ADD CONSTRAINT customers_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES shop.customers(id) ON DELETE SET NULL;
ALTER TABLE shop.order_products ADD CONSTRAINT order_products_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop.orders(id) ON DELETE CASCADE;
ALTER TABLE shop.order_products ADD CONSTRAINT order_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES shop.products(id);
ALTER TABLE shop.orders ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES shop.customers(id) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER TABLE shop.promotions ADD CONSTRAINT promotions_product_id_fkey FOREIGN KEY (product_id) REFERENCES shop.products(id);
ALTER TABLE shop.stock ADD CONSTRAINT stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES shop.products(id);
ALTER TABLE shop.stock ADD CONSTRAINT stock_warehouse_fkey FOREIGN KEY (warehouse_code, region) REFERENCES shop.warehouses(code, region) DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX orders_customer_idx ON shop.orders USING btree (customer_id);
CREATE UNIQUE INDEX orders_note_lower_idx ON shop.orders USING btree (lower(note)) WHERE (note IS NOT NULL);
CREATE INDEX orders_open_idx ON shop.orders USING btree (placed_at DESC) WHERE (status = ANY (ARRAY['placed'::shop.order_status, 'shipped'::shop.order_status]));

CREATE MATERIALIZED VIEW shop.daily_totals AS
SELECT date_trunc('day'::text, placed_at) AS day,
    sum(total) AS total
   FROM shop.orders
  GROUP BY (date_trunc('day'::text, placed_at))
WITH NO DATA;

CREATE VIEW shop.open_orders AS
SELECT id,
    customer_id,
    total
   FROM shop.orders o
  WHERE status = ANY (ARRAY['placed'::shop.order_status, 'shipped'::shop.order_status]);

CREATE VIEW shop.open_orders_by_customer AS
SELECT c.email,
    count(*) AS open_orders
   FROM shop.open_orders oo
     JOIN shop.customers c ON c.id = oo.customer_id
  GROUP BY c.email;

ALTER TABLE shop.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE shop.orders FORCE ROW LEVEL SECURITY;
CREATE POLICY orders_no_cancelled ON shop.orders AS RESTRICTIVE FOR SELECT TO showcase_reader USING (status <> 'cancelled'::shop.order_status);
CREATE POLICY orders_owner ON shop.orders FOR ALL USING (customer_id = (current_setting('app.customer_id'::text))::bigint) WITH CHECK (customer_id = (current_setting('app.customer_id'::text))::bigint);

COMMENT ON TYPE shop.order_status IS 'Lifecycle of an order';
COMMENT ON DOMAIN shop.money_cents IS 'Amounts are integers of cents';
COMMENT ON TABLE shop.customers IS 'People who buy things';
COMMENT ON COLUMN shop.customers.email IS 'Login identifier; unique per customer';
COMMENT ON VIEW shop.open_orders IS 'Orders still in flight';
